//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTTSCMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class LapTop
    {
        public int ID { get; set; }
        public string TenMay { get; set; }
        public System.DateTime NgayNhan { get; set; }
        public System.DateTime NgayGiao { get; set; }
        public string NDSuaChua { get; set; }
        public string ThanhTien { get; set; }
        public int IDNguoiNhanMay { get; set; }
        public int IDChuMay { get; set; }
        public int IDNguoiSuaMay { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
